### ISSUE TITLE
problema con applicazione Health

### ISSUE THREAD

**Issue by PieroAnt** [nathan990315/MIUI_12_Italy#21]
java.util.MissingFormatArgumentException: Format specifier '% d'
	at java.util.Formatter.format(Formatter.java:2523)
	at java.util.Formatter.format(Formatter.java:2459)
	at java.lang.String.format(String.java:2911)
	at android.content.res.Resources.getString(Unknown Source:19)
	at android.content.Context.getString(Unknown Source:4)
	at e.c.g.q.a(Unknown Source:14)
	at d.d.a.G.a.a.h.a(Unknown Source:35)
	at d.d.a.G.a.a.h.a(Unknown Source:1293)
	at d.d.a.G.a.a.i.a(Unknown Source:33)
	at d.d.a.G.a.a.b.apply(Unknown Source:6)
	at b.o.M.a(Unknown Source:4)
	at b.o.x$a.a(Unknown Source:20)
	at androidx.lifecycle.LiveData.a(Unknown Source:29)
	at androidx.lifecycle.LiveData.b(Unknown Source:44)
	at b.o.z.b(Unknown Source:14)
	at b.o.w.run(Unknown Source:18)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loop(Unknown Source:244)
	at android.app.ActivityThread.main(Unknown Source:101)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:275)

**Comment by PieroAnt** [comment]
Cambiando la lingua in inglese funziona senza crash mentre, con la lingua italiana, l'applicazione Salute si chiude immediatamente.

**Comment by BIOLorenz** [comment]
Ciao, analizzo subito il problema, credo sia rimato fuori un campo di valore dinamico...
Ti aggiorno alla risoluzione

**Comment by PieroAnt** [comment]
Ciao, ho cancellato tutti i dati dell'applicazione e funziona nuovamente. Ho dovuto reinserire tutti i dati da zero.

**Comment by BIOLorenz** [comment]
Ciao, tengo aperto.
Il problema sembra presentarsi quando si rimuovono delle opzioni della schermata principale.

**Comment by PieroAnt** [comment]
Ok grazie.
